### ISSUE TITLE
test

### ISSUE THREAD

**Issue by lidox** [lidox/lidox.github.io#2]
![logo](https://user-images.githubusercontent.com/7879175/63674919-ec756480-c7e7-11e9-9c65-80e89c7cc080.png)

**Comment by ghost** [comment]
Hallo Artur, meine Name ist Jan, ich bin Student in Dortmund und arbeite momentan an einem Projekt, dass ich Funkengeber genannt habe. Ich hatte mir dazu auch die .com Adresse gesichert. Mir ist dann später aufgefallen, dass du diese Adresse auch für eine gewisse Zeit genutzt hast. Ist ja auch ein nettes Wortspiel.
Lange Rede, kurzer Sinn, ich wollte fragen, ob es möglich ist, dass du die alten Verweise zu der Seite löschen könntest. Das wäre total nett!
Wir können auch gerne über E-Mail kommunizieren. Ich schreibe hier auf Github, weil ich sonst keine (aktuelle) E-Mail Adresse von dir gefunden habe.
Viele Grüße!

**Comment by ghost** [comment]
Ach, glatt vergessen, hier ist die Mail:
incuerus [at] gmail.com

Ich habe eine ältere Gmail Adresse genommen, damit meine Hauptadresse nicht vielleicht doch von Bots zugespammt wird.
